### ISSUE TITLE
Unable to execute USE SCHEMA and SHOW TABLES command sequentially

### ISSUE THREAD

**Issue by DataEngg** [PythonicNinja/pydrill#12]
I am trying to execute two queries sequentially, like 

1) drill.query(''' USE KarbonnAgg.tadata_new  ''',timeout=360)
2) drill.query(''' SHOW TABLES like \'date%\' ''', timeout=360)

First query executed successfully but second one give an error of USE SCHEMA, So can we add this feature for pydrill.
Better option would be if we can define schema at the time of creating drill connection.

**Comment by PythonicNinja** [comment]
Hello @DataEngg ! Thanks for using pydrill.

In near future I will add my project of pydrill-dsl which will address those kind of issues.
sample: https://gist.github.com/PythonicNinja/9b4952b6cbc17572c7db#file-pydrill_dsl-py

**Comment by PythonicNinja** [comment]
@DataEngg pydrill-dsl has been released
https://github.com/PythonicNinja/pydrill_dsl

**Comment by DataEngg** [comment]
Thanks @PythonicNinja
