### ISSUE TITLE
Performance regarding large object's charset inspection on request

### ISSUE THREAD

**Issue by maxsonic** [PythonicNinja/pydrill#20]
I have encounter a performance issue when loading large object form drill. After profiling and debugging, I found that this is an issue with request on the charset inspection.
If I change the https://github.com/PythonicNinja/pydrill/blob/master/pydrill/connection/requests_conn.py by adding  response.encoding = 'UTF-8'  after line 70, the speed will be improve dramatically.

So I think this performance fix should be considered.

**Comment by PythonicNinja** [comment]
PR: https://github.com/PythonicNinja/pydrill/pull/21
