### ISSUE TITLE
Drill Authentication and Security with PyDrill

### ISSUE THREAD

**Issue by JohnOmernik** [PythonicNinja/pydrill#24]
Hello, I am attempting to use PyDrill, and looking through the code, it appears there is an option to pass http basic auth to pydrill, however, Apache Drill does not use http basic auth, it uses a form based mechanism.  

I really like what pydrill gets long term, and would love the ability to add in the auth component.  

For example, I tried the http_auth (see below), and when I did that, I got an unknown mime error. Based on serializer.py, it's not handling text/html, which if I had to guess, is the mime type returned if the login screen is returned. (I.e. if you submit a query without first authenticating, it shows the login screen which is text/html... I would imaging we would want to handle that at some point. 

So, when I use python requests, to auth to drill, I create a session object and keep it open, with the first thing I do is authenticate.  I am not a great python programmer, so please bear with my simplistic caveman like code. 

But basically, I have create a session object that gets passed around, and the first I do is pass it to the authentication function which makes the login request, and the requests module keeps track of my cookies from that point on. Then from there, all request made to drill work properly.   I would like to use pydrill here, because it provides clean options for handling the ssl certs, etc.  But I would like to be able to use the forms based auth like I have in my hacky scripts. Perhaps I just don't see how to do this, but if it's not in the code, I am hoping this helps us get there... 

Thanks!

## Example script that uses authentication
```
#!/usr/bin/python

import requests
import json
import sys
import os

drill_base_url = "https://drillbit.local:8047"

drill_user = "username"
drill_pass = "password"

print "Drill Rest Endpoint: %s" % (drill_base_url)

def main():
    s = requests.Session() # Create a session object
    s = authDrill(s)        # Authenticate to Drill

    r = runQuery(s, "ALTER SESSION set `store.json.all_text_mode` = true")
    result = runQuery(s, "show files")

    print r.text
    
    if result.status_code == 200:
        print result.text
    else:
        print "Error encountered: %s" % result.status_code

def runQuery(s, drill):
    url = drill_base_url + "/query.json"   
    payload = {"queryType":"SQL", "query":drill}
    headers = {"Content-type": "application/json"}
    r = s.post(url, data=json.dumps(payload), headers=headers, verify=False)

    return r
def authDrill(s):

    url = drill_base_url + "/j_security_check"

    login = {'j_username': drill_user, 'j_password': drill_pass}
   
    r = s.post(url, data=login, verify=False)

    if r.status_code == 200:
        if r.text.find("Invalid username/password credentials") >= 0:
            print "Authentication Failed - Please check Secrets - Exiting"
            sys.exit(1)
        elif r.text.find("Number of Drill Bits") >= 0:
            print "Authentication successful"
        else:
            print "Unknown Response Code 200 - Exiting"
            print r.text
            sys.exit(1)
    else:
        print "Non HTTP-200 returned - Unknown Error - Exiting"
        print "HTTP Code: %s" % r.status_code
        print r.text
        sys.exit(1)

    return s

if __name__ == '__main__':
    main()




```

## Example tried
 import pydrill as PyDrill
drill = PyDrill(host='mydrill.local', port=8047, http_auth="myuser:mypass", use_ssl=True, verify_certs=False)

**Comment by JohnOmernik** [comment]
So I took a whack at this, I forked pydrill https://github.com/JohnOmernik/pydrill and now have it working with only an additional function and some basic changes. It's nice, with the auth it works and I am not sure if issue #12 is still a problem, but with my setup it works without a hitch.  The login succeeds, and then all commands are part of the same session, which is nice.   I am not a python expert, but I tried to mimic how things are setup in the pydrill repo... I'd be curious on thoughts.

**Comment by PythonicNinja** [comment]
@JohnOmernik Hello! I would like to extend pydrill with possibility to authenticate. I had some difficulties setting up PAM authentication for drill-embed on Mac Os X. 

I have followed instruction from https://drill.apache.org/docs/configuring-user-authentication/#installing-and-configuring-pam

My `drill-override`:
```
drill.exec: {
  cluster-id: "drillbits1",
  zk.connect: "localhost:2181",
  http.ssl_enabled: true,
  security.user.auth {
     enabled: true,
     packages += "org.apache.drill.exec.rpc.user.security",
     impl: "pam",
     pam_profiles: [ "sudo", "login" ]
  } 
}
```

I have extracted and exported following env variables:
```
export DRILL_JAVA_LIB_PATH="-Djava.library.path=~/Downloads/JPam-1.1/"
export DRILLBIT_JAVA_OPTS="-Djava.library.path=~/Downloads/JPam-1.1/"
export DRILL_SHELL_JAVA_OPTS="-Djava.library.path=~/Downloads/JPam-1.1/"
```

Tree of that folder:
```
| => tree ~/Downloads/JPam-1.1/
├── CHANGELOG.txt
├── CommonErrors.txt
├── INSTALL.txt
├── JPam-1.1
│   ├── META-INF
│   │   └── MANIFEST.MF
│   └── net
│       └── sf
│           └── jpam
│               ├── Pam.class
│               ├── PamException.class
│               ├── PamReturnValue.class
│               └── jaas
│                   └── JpamLoginModule.class
├── JPam-1.1\ 2
│   ├── c
│   │   ├── Pam.c
│   │   └── makefile
│   ├── config
│   │   ├── HP-UX_ia64
│   │   │   ├── net-sf-jpam
│   │   │   └── net-sf-jpam-securid
│   │   ├── Linux_amd64
│   │   │   ├── net-sf-jpam
│   │   │   └── net-sf-jpam-digipass
│   │   ├── Linux_i386
│   │   │   ├── net-sf-jpam
│   │   │   └── net-sf-jpam-securid
│   │   ├── Linux_x86
│   │   │   ├── net-sf-jpam
│   │   │   └── net-sf-jpam-securid
│   │   ├── Linux_x86_64
│   │   │   ├── net-sf-jpam
│   │   │   └── net-sf-jpam-digipass
│   │   ├── Mac\ OS\ X_i386
│   │   │   └── net-sf-jpam
│   │   ├── Mac\ OS\ X_ppc
│   │   │   └── net-sf-jpam
│   │   └── SunOS_sparc
│   │       ├── net-sf-jpam
│   │       └── net-sf-jpam-securid
│   ├── dist
│   │   ├── CHANGELOG.txt
│   │   ├── CommonErrors.txt
│   │   ├── INSTALL.txt
│   │   └── RELEASE_NOTES.txt
│   ├── java
│   │   └── net
│   │       └── sf
│   │           └── jpam
│   │               ├── Pam.java
│   │               ├── PamException.java
│   │               ├── PamReturnValue.java
│   │               ├── jaas
│   │               │   ├── JpamLoginModule.java
│   │               │   └── package.html
│   │               ├── overview.html
│   │               └── package.html
│   └── rpm
│       ├── jpam.spec
│       └── rpmbuild-nonroot
│           └── README
├── JPam-1.1-javadoc.zip
├── JPam-1.1-src.zip
├── JPam-1.1.jar
├── RELEASE_NOTES.txt
├── libjpam.so
├── net-sf-jpam
└── net-sf-jpam-digipass

25 directories, 44 files
```

Error during drill-embed startup:
```
Error: Failure in starting embedded Drillbit: org.apache.drill.exec.exception.DrillbitStartupException: Problem in finding the native library of JPAM (Pluggable Authenticator Module API). Make sure to set Drillbit JVM option 'java.library.path' to point to the directory where the native JPAM exists.:no jpam in java.library.path (state=,code=0)
```

I would like to test locally authentication, if you could help with my local setup it would be great.

**Comment by JohnOmernik** [comment]
What version of Drill are you running? On the version I am running (1.8) the method for exposing that path is:

# Native library path passed to Java. Note: use this form instead
# of the old form of DRILLBIT_JAVA_OPTS="-Djava.library.path=<dir>"
# The old form is not compatible with Drill-on-YARN.
export DRILL_JAVA_LIB_PATH="/path/to/libjpam.so"

Your drill-override.conf matches mine, but I would look at that component. Also do Mac's use PAM?  I am not sure about that.  Also, I am not sure if Authentication CAN be enabled on Drill-Embed, I using cluster mode, thus, that's not an issue for me... Let me know if the drill-env change above helps and we can keep troubleshooting. 

Thanks!

John

**Comment by PythonicNinja** [comment]
Resolved in https://github.com/PythonicNinja/pydrill/releases/tag/v0.3.1

**Comment by PythonicNinja** [comment]
Implementation details: https://github.com/PythonicNinja/pydrill/commit/d6199199f5a12bb0d29de56859cdd27a7f12ce62

Usage:
```
from pydrill.client import PyDrill
drill = PyDrill(auth='user:password')
```
