### ISSUE TITLE
working with csv files

### ISSUE THREAD

**Issue by RajaPotluri** [PythonicNinja/pydrill#27]
Hi, I started to work with PyDrill and i am using it to extract csv files data by sql query 

from pydrill.client import PyDrill

drill = PyDrill(host='localhost',port=8047)

# if not drill.is_active():
#     raise ImproperlyConfigured('Please run Drill first') --- error do i need to import anything to avoid this?

employees = drill.query('''
  select * from dfs.`C:\\Raja\\apache-drill-1.10\\apache-drill-1.10.0\\sample-data\\sample_data.csv`;
''')

print(employees)

OUTPUT:

POST http://localhost:8047/query.json [status:500 request:0.081s]
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\zk3r80b\AppData\Local\Programs\Python\Python36\lib\site-packages\pydrill-0.3.1-py3.6.egg\pydrill\client\__init__.py", line 62, in query
    'request_timeout': timeout
  File "C:\Users\zk3r80b\AppData\Local\Programs\Python\Python36\lib\site-packages\pydrill-0.3.1-py3.6.egg\pydrill\client\__init__.py", line 24, in perform_request
    return self.transport.perform_request(method, url, params, body)
  File "C:\Users\zk3r80b\AppData\Local\Programs\Python\Python36\lib\site-packages\pydrill-0.3.1-py3.6.egg\pydrill\transport.py", line 79, in perform_request
    timeout=timeout)
  File "C:\Users\zk3r80b\AppData\Local\Programs\Python\Python36\lib\site-packages\pydrill-0.3.1-py3.6.egg\pydrill\connection\requests_conn.py", line 105, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "C:\Users\zk3r80b\AppData\Local\Programs\Python\Python36\lib\site-packages\pydrill-0.3.1-py3.6.egg\pydrill\connection\base.py", line 113, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
pydrill.exceptions.TransportError: TransportError(500, '{\r\n  "errorMessage" : "PARSE ERROR: Encountered \\";\\" at line 2, column 96.\\r\\nWas expecting one of:\\r\\n    <EOF> \\r\\n    \\"ORDER\\" ...\\r\\n    \\"LIMIT\\" ...\\r\\n    \\"OFFSET\\" ...\\r\\n    \\"FETCH\\" ...\\r\\n    \\"NATURAL\\" ...\\r\\n    \\"JOIN\\" ...\\r\\n    \\"INNER\\" ...\\r\\n    \\"LEFT\\" ...\\r\\n    \\"RIGHT\\" ...\\r\\n    \\"FULL\\" ...\\r\\n    \\"CROSS\\" ...\\r\\n    \\",\\" ...\\r\\n    \\"EXTEND\\" ...\\r\\n    \\"(\\" ...\\r\\n    \\"AS\\" ...\\r\\n    <IDENTIFIER> ...\\r\\n    <QUOTED_IDENTIFIER> ...\\r\\n    <BACK_QUOTED_IDENTIFIER> ...\\r\\n    <BRACKET_QUOTED_IDENTIFIER> ...\\r\\n    <UNICODE_QUOTED_IDENTIFIER> ...\\r\\n    \\"TABLESAMPLE\\" ...\\r\\n    \\"WHERE\\" ...\\r\\n    \\"GROUP\\" ...\\r\\n    \\"HAVING\\" ...\\r\\n    \\"WINDOW\\" ...\\r\\n    \\"UNION\\" ...\\r\\n    \\"INTERSECT\\" ...\\r\\n    \\"EXCEPT\\" ...\\r\\n    \\".\\" ...\\r\\n    \\"[\\" ...\\r\\n    \\n\\nSQL Query \\n  select * from dfs.`C:\\\\Raja\\\\apache-drill-1.10\\\\apache-drill-1.10.0\\\\sample-data\\\\sample_data.csv`;\\n                                                                                               ^\\n\\n\\n[Error Id: a7af5d2a-d899-4631-9a70-e1ec30f91f70 on F480FCF64F84F.corp.bankofamerica.com:31010]"\r\n}')

could you help me fix this ? 

Is there any documentation of code to work with PyDrill and Apache-Drill

**Comment by asettouf** [comment]
Didn't you simply forget the backticks around the filepath? (See https://drill.apache.org/docs/file-system-storage-plugin/) Your query should be like:

```
employees = drill.query('''
select * from dfs.`C:\\Raja\\apache-drill-1.10\\apache-drill-1.10.0\\sample-data\\sample_data.csv`
''')
```

**Comment by PythonicNinja** [comment]
@RajaPotluri Seems to be related to the query issue, not pydrill related.
