### ISSUE TITLE
how to get all of column name?

### ISSUE THREAD

**Issue by 521xueweihan** [PythonicNinja/pydrill#28]
The ResultQuery return  generator，so I can't use index get all the column names.

Can't use next too, so how can I get all result column name ?

**Comment by 521xueweihan** [comment]
```
for result in yelp_reviews:
    column_names = result.keys()
    break
```

**Comment by PythonicNinja** [comment]
Indeed, that's one of the possible solutions to your problem.
You could also:
`column_names = yelp_reviews[0].keys()`

**Comment by 521xueweihan** [comment]
I try your solutions, It will raise error: `'ResultQuery' object does not support indexing`
generator, can't index.

**Comment by PythonicNinja** [comment]
`column_names = list(yelp_reviews)[0].keys()` should work fine

**Comment by 521xueweihan** [comment]
Thanks for your reply.I think `list()` need more space, but It look more sample.

**Comment by PythonicNinja** [comment]
@521xueweihan `next(yelp_reviews).keys()` is also possible
